import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Colors, DarkColors } from '../constants/colors';

export type Language = 'fr' | 'en';
export type Currency = 'EUR' | 'MAD';

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  fr: {
    // Common
    common_save: 'Enregistrer',
    common_cancel: 'Annuler',
    common_delete: 'Supprimer',
    common_edit: 'Modifier',
    common_add: 'Ajouter',
    common_back: 'Retour',
    common_confirm: 'Confirmer',
    common_all: 'Tout',
    common_yes: 'Oui',
    common_no: 'Non',
    common_loading: 'Chargement...',
    common_error: 'Erreur',
    common_optional: 'Optionnel',
    common_required: 'Requis',
    common_name_required: 'Nom requis',
    // Tabs
    tabs_home: 'Accueil',
    tabs_planner: 'Planning',
    tabs_recipes: 'Recettes',
    tabs_shopping: 'Courses',
    tabs_budget: 'Budget',
    tabs_stock: 'Stock',
    // Wellness
    wellness_balanced: 'Équilibré',
    wellness_quick: 'Rapide',
    wellness_indulgent: 'Plaisir',
    // Meals
    meal_breakfast: 'Petit-déj.',
    meal_breakfast_full: 'Petit-déjeuner',
    meal_lunch: 'Déjeuner',
    meal_dinner: 'Dîner',
    // Dashboard
    dashboard_greeting_morning: 'Bonjour',
    dashboard_greeting_afternoon: 'Bon après-midi',
    dashboard_greeting_evening: 'Bonsoir',
    dashboard_next_meal: 'Prochain repas',
    dashboard_nothing_planned: 'Rien de planifié',
    dashboard_weekly_spend: 'Dépenses semaine',
    dashboard_meals: 'repas',
    dashboard_avg_day: 'moy./jour',
    dashboard_recipes_count: 'recettes',
    dashboard_today_menu: 'Menu du jour',
    dashboard_wellness: 'Équilibre alimentaire',
    dashboard_this_week: 'Cette semaine',
    dashboard_next_badge: 'Suivant',
    dashboard_not_planned: 'Non planifié',
    dashboard_variety_score: 'Variété',
    dashboard_total_planned: 'Planifiés',
    dashboard_wellness_score: 'Équilibre',
    dashboard_recipes_label: 'Recettes',
    dashboard_meals_label: 'Repas / sem.',
    dashboard_tip_over: 'Budget dépassé. Remplacez un repas par une soupe économique.',
    dashboard_tip_ok: 'Budget bien géré. Continuez ainsi !',
    dashboard_settings: 'Paramètres',
    dashboard_per_person: '/pers.',
    dashboard_pantry_title: 'Garde-manger',
    dashboard_pantry_count: 'ingrédient(s) en stock',
    dashboard_pantry_empty: 'Gérez votre stock',
    // Recipes
    recipes_title: 'Recettes',
    recipes_add: 'Ajouter',
    recipes_search: 'Rechercher...',
    recipes_no_results: 'Aucun résultat.',
    recipes_create_first: 'Créez votre première recette.',
    recipes_none: 'Aucune recette',
    recipes_count_one: 'recette',
    recipes_count_many: 'recettes',
    recipes_min: 'min',
    recipes_pers: 'pers.',
    recipes_scan: 'Scanner',
    // Shopping
    shopping_title: 'Courses',
    shopping_add_item: 'Ajouter un article',
    shopping_empty_title: 'Liste vide',
    shopping_empty_desc: 'Ajoutez vos articles de courses.',
    shopping_to_buy: 'À acheter',
    shopping_in_cart: 'Dans le panier',
    shopping_total: 'Total estimé',
    shopping_articles: 'Articles',
    shopping_checked: 'Cochés',
    shopping_subtotal: 'Sous-total',
    shopping_item_name: 'Nom de l\'article',
    shopping_quantity: 'Quantité',
    shopping_unit: 'Unité',
    shopping_price_unit: 'Prix unitaire',
    shopping_clear_checked: 'Effacer cochés',
    shopping_delete_confirm: 'Supprimer cet article ?',
    shopping_new_item: 'Nouvel article',
    shopping_generate: 'Générer depuis le planning',
    shopping_generate_title: 'Générer la liste de courses',
    shopping_generate_desc: 'Importez les ingrédients manquants à partir de vos repas planifiés cette semaine.',
    shopping_generate_no_plan: 'Aucun repas planifié cette semaine.',
    shopping_generate_replace: 'Remplacer la liste',
    shopping_generate_merge: 'Fusionner avec la liste',
    shopping_generate_btn: 'Générer',
    shopping_generate_done: 'articles ajoutés',
    shopping_generate_in_stock: 'déjà en stock',
    shopping_add_to_stock_title: 'Ajouter au stock ?',
    shopping_add_to_stock_yes: 'Ajouter au stock',
    shopping_progress: 'Progression',
    shopping_remaining_label: 'restants',
    shopping_in_cart_strip: 'dans le panier',
    shopping_total_strip: 'total estimé',
    shopping_items: 'articles',
    shopping_done: 'fait',
    // Notifications
    settings_notifications: 'Rappels repas',
    settings_notifications_sub: 'Notifications quotidiennes pour chaque repas',
    settings_notifications_breakfast: 'Petit-déjeuner',
    settings_notifications_lunch: 'Déjeuner',
    settings_notifications_dinner: 'Dîner',
    settings_notifications_permission: 'Permission notifications refusée. Activez-la dans les réglages de votre téléphone.',
    // Cooking
    cooking_deduct_title: 'Cuisine terminée !',
    cooking_deduct_question: 'Déduire les ingrédients utilisés de votre garde-manger ?',
    cooking_deduct_yes: 'Mettre à jour le stock',
    cooking_deduct_no: 'Non, terminer',
    // Budget history
    budget_history: 'Historique',
    budget_prev_weeks: 'Semaines précédentes',
    budget_no_history: 'Aucun historique disponible',
    budget_week_of: 'Semaine du',
    // Planner
    planner_title: 'Planning',
    planner_week_of: 'Semaine du',
    planner_add_meal: 'Ajouter un repas',
    planner_choose_recipe: 'Choisir une recette',
    planner_no_recipes: 'Aucune recette disponible.',
    planner_day_cost: 'Coût du jour',
    planner_meals_planned: 'repas planifiés',
    planner_clear_slot: 'Vider le créneau',
    planner_overview: 'Vue semaine',
    planner_custom_meal: 'Saisir un repas libre',
    planner_or_recipe: 'ou choisir une recette',
    planner_search_recipe: 'Rechercher une recette…',
    planner_today: "Aujourd'hui",
    planner_day_mon: 'Lundi',
    planner_day_tue: 'Mardi',
    planner_day_wed: 'Mercredi',
    planner_day_thu: 'Jeudi',
    planner_day_fri: 'Vendredi',
    planner_day_sat: 'Samedi',
    planner_day_sun: 'Dimanche',
    planner_day_short_mon: 'L',
    planner_day_short_tue: 'M',
    planner_day_short_wed: 'M',
    planner_day_short_thu: 'J',
    planner_day_short_fri: 'V',
    planner_day_short_sat: 'S',
    planner_day_short_sun: 'D',
    // Budget
    budget_title: 'Budget',
    // Settings
    settings_title: 'Paramètres',
    settings_language: 'Langue',
    settings_currency: 'Devise',
    settings_french: 'Français',
    settings_english: 'English',
    settings_eur: 'Euro (€)',
    settings_mad: 'Dirham marocain (MAD)',
    settings_account: 'Compte',
    settings_logout: 'Se déconnecter',
    settings_app: 'Application',
    settings_preferences: 'Préférences',
    settings_logout_confirm: 'Se déconnecter de votre compte ?',
    settings_darkmode: 'Mode sombre',
    settings_darkmode_sub: 'Thème sombre pour les yeux',
    settings_help: 'Aide & guide',
    settings_help_title: 'Comment utiliser Eatsy',
    settings_copyright: 'À propos',
    settings_version: 'Version',
    settings_copyright_text: '© 2025 Eatsy. Tous droits réservés.',
    settings_appearance: 'Apparence',
    help_planner_title: 'Planning hebdomadaire',
    help_planner_desc: 'Planifiez vos repas (petit-déj., déjeuner, dîner) pour chaque jour de la semaine. Appuyez sur un créneau pour choisir une recette.',
    help_recipes_title: 'Recettes',
    help_recipes_desc: 'Créez et gérez vos recettes. Utilisez le scanner pour ajouter des ingrédients depuis un code-barres.',
    help_shopping_title: 'Liste de courses',
    help_shopping_desc: 'Ajoutez vos articles et cochez-les au fur et à mesure de vos achats. Le total estimé se calcule automatiquement.',
    help_budget_title: 'Budget',
    help_budget_desc: 'Suivez vos dépenses hebdomadaires. Le budget est calculé à partir du coût de vos repas planifiés.',
    help_pantry_title: 'Garde-manger',
    help_pantry_desc: 'Gérez votre stock d\'ingrédients à la maison. Mettez à jour les quantités après vos courses.',
    // Loading
    loading_1: 'Préparation de vos recettes…',
    loading_2: 'Calcul de votre budget hebdomadaire…',
    loading_3: 'Chargement de votre planning…',
    loading_4: 'Cuisinez malin avec Eatsy.',
    loading_5: 'Votre semaine culinaire se prépare…',
    loading_6: 'Synchronisation de vos listes de courses…',
    // Auth
    auth_email_required: 'Email requis',
    auth_email_invalid: 'Email invalide',
    auth_password_required: 'Mot de passe requis',
    auth_password_min: 'Au moins 6 caractères',
    auth_passwords_mismatch: 'Les mots de passe ne correspondent pas',
    // Login
    login_title: 'Connexion',
    login_tagline: 'Planifiez. Cuisinez. Économisez.',
    login_error_title: 'Erreur de connexion',
    login_error_msg: 'Email ou mot de passe incorrect.',
    login_forgot: 'Mot de passe oublié ?',
    login_create_account: 'Créer un compte',
    login_or: 'ou',
    // Register
    register_title: 'Créer un compte',
    register_sub: 'Rejoignez la table curatée.',
    register_name_label: 'Nom complet',
    register_name_placeholder: 'Marie Dupont',
    register_email_label: 'Adresse e-mail',
    register_pwd_label: 'Mot de passe',
    register_pwd_placeholder: 'Min. 6 caractères',
    register_confirm_label: 'Confirmer le mot de passe',
    register_btn: 'Créer mon compte',
    register_login_link: 'Déjà inscrit ? Se connecter',
    register_failed: 'Inscription échouée',
    // Forgot password
    forgot_title: 'Mot de passe oublié ?',
    forgot_sub: "Saisissez votre email et nous vous enverrons\nun lien de réinitialisation.",
    forgot_email_label: 'Adresse e-mail',
    forgot_email_placeholder: 'votre@email.com',
    forgot_send_btn: 'Envoyer le lien',
    forgot_back_link: '← Retour à la connexion',
    forgot_success_title: 'Email envoyé !',
    forgot_success_desc: 'Vérifiez votre boîte mail et suivez les instructions pour réinitialiser votre mot de passe.',
    forgot_back_to_login: 'Retour à la connexion',
    forgot_failed: "Échec de l'envoi",
    // Welcome
    welcome_greeting: 'Bienvenue 👋',
    welcome_tagline: 'Planifiez · Cuisinez · Économisez',
    // Lock
    lock_title: 'Application verrouillée',
    lock_sub_face: "Utilisez Face ID\nou le code PIN de votre appareil",
    lock_sub_finger: "Utilisez votre empreinte digitale\nou le code PIN de votre appareil",
    lock_sub_default: "Utilisez la biométrie\nou le code PIN de votre appareil",
    lock_unlock: 'Déverrouiller',
    lock_prompt: 'Déverrouiller Eatsy',
    lock_fallback: 'Utiliser le code PIN',
    lock_cancelled: 'Authentification annulée.',
    lock_error: "Erreur d'authentification.",
    // Onboarding
    onboarding_skip: 'Passer',
    onboarding_slide1_title: 'Planifiez votre semaine',
    onboarding_slide1_desc: 'Organisez petit-déjeuner, déjeuner et dîner pour chaque jour. Votre planning culinaire toujours sous la main.',
    onboarding_slide2_title: 'Maîtrisez votre budget',
    onboarding_slide2_desc: 'Suivez vos dépenses alimentaires semaine par semaine. Eatsy calcule le coût de chaque repas automatiquement.',
    onboarding_slide3_title: 'Cuisinez malin',
    onboarding_slide3_desc: 'Générez votre liste de courses en un clic, gérez votre garde-manger et retrouvez toutes vos recettes en un endroit.',
    onboarding_next: 'Suivant',
    onboarding_start: 'Commencer',
    // Settings — security & help
    settings_security: 'SÉCURITÉ',
    settings_biometric_face: 'Face ID',
    settings_biometric_fingerprint: 'Empreinte digitale',
    settings_biometric_pin: 'Code PIN',
    settings_biometric_default: 'Biométrie',
    settings_biometric_sub_on: "Verrouille l'app après 30 s en arrière-plan",
    settings_biometric_sub_off: 'Non disponible sur cet appareil',
    settings_biometric_confirm: "Confirmer l'activation",
    settings_help_show: "Afficher le guide d'utilisation",
    settings_help_hide: 'Masquer le guide',
    settings_terms_show: "Lire les conditions d'utilisation",
    settings_terms_hide: 'Masquer les conditions',
    // Add recipe
    add_recipe_title_new: 'Nouvelle recette',
    add_recipe_title_edit: 'Modifier la recette',
    add_recipe_change_photo: 'Changer',
    add_recipe_add_photo: 'Ajouter une photo',
    add_recipe_photo_hint: 'Optionnel · JPG, PNG',
    add_recipe_general: 'Informations générales',
    add_recipe_name_label: 'Nom de la recette *',
    add_recipe_name_placeholder: 'Ex: Poulet rôti aux herbes',
    add_recipe_prep_label: 'Préparation (min)',
    add_recipe_cook_label: 'Cuisson (min)',
    add_recipe_servings_label: 'Portions',
    add_recipe_category: 'Catégorie',
    add_recipe_ingredients: 'Ingrédients',
    add_recipe_quantity: 'Quantité',
    add_recipe_unit: 'Unité',
    add_recipe_add_ingredient: 'Ajouter un ingrédient',
    add_recipe_add_step: 'Ajouter une étape',
    add_recipe_save_new: 'Créer la recette',
    add_recipe_save_edit: 'Enregistrer les modifications',
    add_recipe_incomplete_title: 'Ingrédient incomplet',
    add_recipe_incomplete_msg: 'Tous les ingrédients doivent avoir un nom.',
    add_recipe_name_required_msg: 'Veuillez saisir un nom pour la recette.',
    add_recipe_meal_type: 'Type de repas',
    add_recipe_desc_label: 'Description',
    add_recipe_desc_placeholder: 'Courte description...',
    add_recipe_ing_name: 'Nom',
    add_recipe_ingredient_n: 'Ingrédient',
    add_recipe_step_placeholder: 'Décrivez l\'étape {n}...',
    add_recipe_instructions: 'Instructions',
    // Recipe detail
    recipe_stat_prep: 'Prép.',
    recipe_stat_cook: 'Cuisson',
    recipe_stat_servings: 'Portions',
    recipe_stat_per_person: 'Par pers.',
    recipe_total_cost: 'Coût total de la recette',
    recipe_ingredient_total: 'Total ingrédients',
    recipe_deduct_btn: 'Déduire',
    recipe_start_cooking: 'Démarrer la cuisine',
    recipe_stock_empty: 'Stock insuffisant',
    recipe_stock_empty_msg: 'Aucun ingrédient trouvé dans votre garde-manger.',
    recipe_deduct_title: 'Déduire du stock',
    recipe_deduct_done: 'Stock mis à jour',
    recipe_deduct_done_msg: 'Les ingrédients ont été déduits de votre garde-manger.',
    recipe_added_shopping: 'Ajouté aux courses',
    recipe_delete_title: 'Supprimer la recette',
    recipe_delete_confirm_msg: 'Supprimer "{name}" définitivement ?',
    recipe_deduct_confirm_msg: 'Déduire les ingrédients de "{name}" de votre garde-manger ?',
    recipe_added_shopping_msg: '{n} ingrédient(s) ajouté(s) à votre liste de courses.',
    recipe_in_stock: 'Stock disponible',
    recipe_stock_complete: 'complets',
    recipe_stock_partial: 'partiels',
    recipe_stock_missing: 'manquants',
    recipe_stock_dispo: 'dispo',
    recipe_stock_out: 'non en stock',
    recipe_shopping_list_btn: 'Courses',
    recipe_share_btn: 'Partager la recette',
    recipe_share_cost: 'Coût estimé',
    recipe_tab_ingredients: 'Ingrédients',
    recipe_tab_instructions: 'Instructions',
    // Cooking
    cooking_step: 'Étape',
    cooking_step_of: 'sur',
    cooking_last_step: 'Dernière étape',
    cooking_prev: 'Précédent',
    cooking_finish: 'Terminer',
    cooking_timer: 'Minuteur',
    cooking_start_timer: 'Démarrer',
    cooking_pause_timer: 'Pause',
    cooking_all_steps: 'Toutes les étapes',
    cooking_timer_done: 'Le temps est écoulé !',
    cooking_recipe_done: 'La recette est terminée.',
    // Budget
    budget_over_label: 'dépassement',
    budget_remaining_label: 'restant',
    budget_avg_label: 'moy. / jour',
    budget_limit_label: 'limite fixée',
    budget_per_day: 'Par jour',
    budget_progress_label: 'Progression budgétaire',
    budget_no_meals_day: 'Aucun repas planifié',
    budget_this_week: 'Cette\nsem.',
    // Dashboard
    dashboard_over_budget: 'Dépassé',
    dashboard_on_track: 'Dans les clous',
    // Food scanner
    scanner_camera_title: 'Scanner un produit',
    scanner_permission: 'Autorisation caméra requise',
    scanner_allow: 'Autoriser',
    scanner_product_not_found: 'Produit non trouvé',
    scanner_barcode_label: 'Code-barres',
    scanner_rescan: 'Rescanner',
    scanner_close: 'Fermer',
    scanner_network_error: 'Erreur réseau',
    scanner_network_error_msg: 'Impossible de récupérer les informations produit.',
    scanner_added_to_cart: 'Ajouté aux courses',
    scanner_added_to_cart_msg: 'ajouté à votre liste de courses.',
    scanner_scan_another: 'Scanner un autre',
    scanner_added_to_stock: 'Ajouté au stock',
    scanner_added_to_stock_msg: 'ajouté à votre garde-manger.',
    scanner_unknown: 'Produit inconnu',
    scanner_nutrition: 'Valeurs nutritionnelles / 100g',
    scanner_quantity: 'Quantité',
    scanner_rescan_product: 'Scanner un autre produit',
    scanner_cart_btn: 'Courses',
    scanner_stock_btn: 'Mon Stock',
    scanner_energy: 'Énergie',
    scanner_proteins: 'Protéines',
    scanner_carbs: 'Glucides',
    scanner_fat: 'Lipides',
    // Pantry
    pantry_depleted: 'épuisés',
    pantry_search_ph: 'Rechercher un ingrédient…',
    pantry_filter_available: 'Disponibles',
    pantry_filter_empty: 'Épuisés',
    pantry_exhausted: 'Épuisé',
    pantry_empty_title: 'Garde-manger vide',
    pantry_empty_no_results: 'Aucun résultat',
    pantry_empty_no_match: 'Aucun ingrédient ici',
    pantry_empty_desc: 'Ajoutez vos ingrédients disponibles pour suivre votre stock.',
    pantry_empty_filter_desc: 'Changez le filtre pour voir vos ingrédients.',
    pantry_add_btn: 'Ajouter un ingrédient',
    pantry_sheet_add: 'Ajouter au stock',
    pantry_label_ingredient: 'Ingrédient *',
    pantry_placeholder_ingredient: 'Ex: Bœuf, Farine, Lait…',
    pantry_label_quantity: 'Quantité *',
    pantry_label_unit: 'Unité',
    pantry_save_update: 'Mettre à jour',
    // Profile
    profile_title: 'Profil',
    profile_member_since: 'membre depuis',
    profile_status_email: 'statut email',
    profile_verified: 'Vérifié',
    profile_not_verified: 'Non vérifié',
    profile_change_name: 'Changer votre nom affiché',
    profile_update_creds: 'Mettre à jour vos identifiants',
    profile_verify_title: "Vérifier l'adresse e-mail",
    profile_verify_sub: 'Un lien sera envoyé à votre adresse',
    profile_verify_sent: 'Email envoyé — vérifiez votre boîte',
    profile_check_verified: 'J\'ai vérifié mon email',
    profile_check_verified_sub: 'Appuyez ici après avoir cliqué sur le lien',
    profile_settings_link: 'Paramètres',
    profile_display_name_label: 'Nom affiché',
    profile_email_label: 'Adresse e-mail',
    profile_pwd_current_label: 'Mot de passe actuel',
    profile_pwd_new_label: 'Nouveau mot de passe',
    profile_pwd_confirm_label: 'Confirmer',
    profile_pwd_current_required: 'Mot de passe actuel requis',
    profile_pwd_new_required: 'Nouveau mot de passe requis',
    profile_pwd_wrong: 'Mot de passe actuel incorrect',
    profile_pwd_changed: 'Votre mot de passe a été modifié.',
    profile_verified_success: 'Email vérifié ✓',
    profile_verified_msg: 'Votre adresse e-mail a bien été vérifiée.',
    profile_not_verified_yet: 'Pas encore vérifié',
    profile_error_profile: 'Impossible de modifier le profil',
    profile_error_pwd: 'Impossible de modifier le mot de passe',
    profile_error_verify: "Impossible d'envoyer l'email de vérification",
    profile_email_sent_title: 'Email envoyé',
    profile_too_many: 'Trop de tentatives',
    profile_too_many_msg: 'Attendez quelques minutes avant de renvoyer un email.',
    profile_section_info: 'INFORMATIONS',
    profile_section_security: 'SÉCURITÉ',
    // Budget (new)
    budget_evolution: 'Évolution des dépenses',
    budget_over_prefix: 'Dépassement de',
    budget_pct_used: 'utilisé',
    budget_modal_title: 'Budget hebdomadaire',
    budget_modal_desc: 'Définissez votre limite de dépenses pour la semaine.',
    budget_modal_limit: 'Limite',
    // Dashboard / Common (new)
    dashboard_cook_btn: 'Cuisiner',
    tabs_scanner: 'Scanner',
    common_chef: 'Chef',
    common_success: 'Succès',
    // Pantry (new)
    pantry_total_label: 'total',
    pantry_available_label: 'disponibles',
    pantry_depleted_label: 'épuisés',
    pantry_ingredients_total: '{n} ingrédient(s) au total',
    pantry_sheet_edit: 'Modifier "{name}"',
    pantry_current_stock: 'Stock actuel',
    pantry_save_add: 'Ajouter',
    pantry_search_match_desc: 'Aucun ingrédient correspondant à "{query}".',
    // Profile (new)
    profile_section_account: 'INFORMATIONS DU COMPTE',
    profile_section_actions: 'ACTIONS',
    profile_edit_title: 'Modifier le profil',
    profile_change_pwd: 'Modifier le mot de passe',
    profile_name_placeholder: 'Votre nom',
    profile_pwd_confirm_full: 'Confirmer le nouveau mot de passe',
    profile_verif_link_msg: "Un lien de vérification a été envoyé à {email}. Cliquez sur le lien puis revenez ici.",
    profile_not_verified_msg: "Cliquez sur le lien dans l'email de vérification puis réessayez.",
    // Settings (new)
    settings_data_section: 'DONNÉES & CONFIDENTIALITÉ',
    settings_biometric_lock: 'Verrouillage {type}',
    settings_faq_q1: "Mes données sont-elles partagées avec des tiers ?",
    settings_faq_a1: "Non. Vos données (recettes, planning, budget) sont stockées sur votre compte Firebase personnel et ne sont jamais partagées, vendues ou transmises à des tiers.",
    settings_faq_q2: "L'application fonctionne-t-elle hors ligne ?",
    settings_faq_a2: "Certaines données récemment consultées sont mises en cache par Firebase, mais la plupart des fonctionnalités nécessitent une connexion internet pour synchroniser vos données en temps réel.",
    settings_faq_q3: "Comment supprimer mon compte et mes données ?",
    settings_faq_a3: "Pour supprimer votre compte et toutes vos données, contactez le support depuis la section À propos. La suppression est définitive et irréversible.",
    settings_faq_q4: "Puis-je utiliser Eatsy sur plusieurs appareils ?",
    settings_faq_a4: "Oui. Vos données sont synchronisées via votre compte et accessibles sur tous vos appareils connectés avec les mêmes identifiants.",
    settings_faq_q5: "Comment sont calculés les coûts des recettes ?",
    settings_faq_a5: "Le coût d'une recette est la somme des prix unitaires de ses ingrédients, que vous renseignez lors de la création. Le coût par personne est ensuite calculé en divisant par le nombre de portions.",
    settings_faq_q6: "Mes données sont-elles sécurisées ?",
    settings_faq_a6: "Oui. Les données sont chiffrées en transit (HTTPS) et au repos dans l'infrastructure Google Firebase, soumise aux normes ISO 27001 et SOC 2.",
    settings_terms_t1: 'Données collectées',
    settings_terms_b1: "Eatsy collecte votre nom, adresse e-mail, recettes, planning de repas, liste de courses, budget et données de garde-manger. Ces données sont nécessaires au bon fonctionnement de l'application.",
    settings_terms_t2: 'Stockage & sécurité',
    settings_terms_b2: "Vos données sont stockées sur Firebase (Google LLC), chiffrées en transit (TLS) et au repos. L'infrastructure est certifiée ISO 27001 et SOC 2 Type II.",
    settings_terms_t3: 'Partage des données',
    settings_terms_b3: "Aucune donnée personnelle n'est partagée, vendue ou cédée à des tiers à des fins commerciales. Eatsy n'utilise pas de traceurs publicitaires.",
    settings_terms_t4: 'Droit à la suppression',
    settings_terms_b4: "Vous pouvez demander la suppression définitive de votre compte et de toutes vos données à tout moment en nous contactant. La suppression est effective sous 30 jours.",
    settings_terms_t5: 'Mise à jour des conditions',
    settings_terms_b5: "Ces conditions peuvent être mises à jour. Vous serez informé par notification en cas de changement significatif. L'utilisation continue de l'app vaut acceptation.",
  },
  en: {
    // Common
    common_save: 'Save',
    common_cancel: 'Cancel',
    common_delete: 'Delete',
    common_edit: 'Edit',
    common_add: 'Add',
    common_back: 'Back',
    common_confirm: 'Confirm',
    common_all: 'All',
    common_yes: 'Yes',
    common_no: 'No',
    common_loading: 'Loading...',
    common_error: 'Error',
    common_optional: 'Optional',
    common_required: 'Required',
    common_name_required: 'Name required',
    // Tabs
    tabs_home: 'Home',
    tabs_planner: 'Planner',
    tabs_recipes: 'Recipes',
    tabs_shopping: 'Shopping',
    tabs_budget: 'Budget',
    tabs_stock: 'Stock',
    // Wellness
    wellness_balanced: 'Balanced',
    wellness_quick: 'Quick',
    wellness_indulgent: 'Indulgent',
    // Meals
    meal_breakfast: 'Breakfast',
    meal_breakfast_full: 'Breakfast',
    meal_lunch: 'Lunch',
    meal_dinner: 'Dinner',
    // Dashboard
    dashboard_greeting_morning: 'Good morning',
    dashboard_greeting_afternoon: 'Good afternoon',
    dashboard_greeting_evening: 'Good evening',
    dashboard_next_meal: 'Next meal',
    dashboard_nothing_planned: 'Nothing planned',
    dashboard_weekly_spend: 'Weekly spending',
    dashboard_meals: 'meals',
    dashboard_avg_day: 'avg/day',
    dashboard_recipes_count: 'recipes',
    dashboard_today_menu: "Today's menu",
    dashboard_wellness: 'Food balance',
    dashboard_this_week: 'This week',
    dashboard_next_badge: 'Next',
    dashboard_not_planned: 'Not planned',
    dashboard_variety_score: 'Variety',
    dashboard_total_planned: 'Planned',
    dashboard_wellness_score: 'Balance',
    dashboard_recipes_label: 'Recipes',
    dashboard_meals_label: 'Meals / week',
    dashboard_tip_over: 'Budget exceeded. Try replacing a meal with a budget soup.',
    dashboard_tip_ok: 'Budget well managed. Keep it up!',
    dashboard_settings: 'Settings',
    dashboard_per_person: '/person',
    dashboard_pantry_title: 'Pantry',
    dashboard_pantry_count: 'ingredient(s) in stock',
    dashboard_pantry_empty: 'Manage your stock',
    // Recipes
    recipes_title: 'Recipes',
    recipes_add: 'Add',
    recipes_search: 'Search...',
    recipes_no_results: 'No results.',
    recipes_create_first: 'Create your first recipe.',
    recipes_none: 'No recipes',
    recipes_count_one: 'recipe',
    recipes_count_many: 'recipes',
    recipes_min: 'min',
    recipes_pers: 'serv.',
    recipes_scan: 'Scan',
    // Shopping
    shopping_title: 'Shopping',
    shopping_add_item: 'Add item',
    shopping_empty_title: 'Empty list',
    shopping_empty_desc: 'Add your shopping items.',
    shopping_to_buy: 'To buy',
    shopping_in_cart: 'In cart',
    shopping_total: 'Estimated total',
    shopping_articles: 'Items',
    shopping_checked: 'Checked',
    shopping_subtotal: 'Cart subtotal',
    shopping_item_name: 'Item name',
    shopping_quantity: 'Quantity',
    shopping_unit: 'Unit',
    shopping_price_unit: 'Unit price',
    shopping_clear_checked: 'Clear checked',
    shopping_delete_confirm: 'Delete this item?',
    shopping_new_item: 'New item',
    shopping_generate: 'Generate from planner',
    shopping_generate_title: 'Generate shopping list',
    shopping_generate_desc: 'Import missing ingredients from your planned meals this week.',
    shopping_generate_no_plan: 'No meals planned this week.',
    shopping_generate_replace: 'Replace list',
    shopping_generate_merge: 'Merge with list',
    shopping_generate_btn: 'Generate',
    shopping_generate_done: 'items added',
    shopping_generate_in_stock: 'already in stock',
    shopping_add_to_stock_title: 'Add to pantry?',
    shopping_add_to_stock_yes: 'Add to pantry',
    shopping_progress: 'Progress',
    shopping_remaining_label: 'remaining',
    shopping_in_cart_strip: 'in cart',
    shopping_total_strip: 'estimated total',
    shopping_items: 'items',
    shopping_done: 'done',
    // Notifications
    settings_notifications: 'Meal reminders',
    settings_notifications_sub: 'Daily notifications for each meal',
    settings_notifications_breakfast: 'Breakfast',
    settings_notifications_lunch: 'Lunch',
    settings_notifications_dinner: 'Dinner',
    settings_notifications_permission: 'Notification permission denied. Enable it in your phone settings.',
    // Cooking
    cooking_deduct_title: 'Cooking done!',
    cooking_deduct_question: 'Deduct used ingredients from your pantry?',
    cooking_deduct_yes: 'Update stock',
    cooking_deduct_no: 'No, finish',
    // Budget history
    budget_history: 'History',
    budget_prev_weeks: 'Previous weeks',
    budget_no_history: 'No history available',
    budget_week_of: 'Week of',
    // Planner
    planner_title: 'Planner',
    planner_week_of: 'Week of',
    planner_add_meal: 'Add a meal',
    planner_choose_recipe: 'Choose a recipe',
    planner_no_recipes: 'No recipes available.',
    planner_day_cost: 'Day cost',
    planner_meals_planned: 'meals planned',
    planner_clear_slot: 'Clear slot',
    planner_overview: 'Week overview',
    planner_custom_meal: 'Enter a free meal',
    planner_or_recipe: 'or choose a recipe',
    planner_search_recipe: 'Search a recipe…',
    planner_today: 'Today',
    planner_day_mon: 'Monday',
    planner_day_tue: 'Tuesday',
    planner_day_wed: 'Wednesday',
    planner_day_thu: 'Thursday',
    planner_day_fri: 'Friday',
    planner_day_sat: 'Saturday',
    planner_day_sun: 'Sunday',
    planner_day_short_mon: 'M',
    planner_day_short_tue: 'T',
    planner_day_short_wed: 'W',
    planner_day_short_thu: 'T',
    planner_day_short_fri: 'F',
    planner_day_short_sat: 'S',
    planner_day_short_sun: 'S',
    // Budget
    budget_title: 'Budget',
    // Settings
    settings_title: 'Settings',
    settings_language: 'Language',
    settings_currency: 'Currency',
    settings_french: 'Français',
    settings_english: 'English',
    settings_eur: 'Euro (€)',
    settings_mad: 'Moroccan Dirham (MAD)',
    settings_account: 'Account',
    settings_logout: 'Sign out',
    settings_app: 'App',
    settings_preferences: 'Preferences',
    settings_logout_confirm: 'Sign out of your account?',
    settings_darkmode: 'Dark mode',
    settings_darkmode_sub: 'Dark theme for your eyes',
    settings_help: 'Help & guide',
    settings_help_title: 'How to use Eatsy',
    settings_copyright: 'About',
    settings_version: 'Version',
    settings_copyright_text: '© 2025 Eatsy. All rights reserved.',
    settings_appearance: 'Appearance',
    help_planner_title: 'Weekly Planner',
    help_planner_desc: 'Plan your meals (breakfast, lunch, dinner) for each day of the week. Tap a slot to choose a recipe.',
    help_recipes_title: 'Recipes',
    help_recipes_desc: 'Create and manage your recipes. Use the scanner to add ingredients from a barcode.',
    help_shopping_title: 'Shopping List',
    help_shopping_desc: 'Add items and check them off as you shop. The estimated total is calculated automatically.',
    help_budget_title: 'Budget',
    help_budget_desc: 'Track your weekly spending. Budget is calculated from the cost of your planned meals.',
    help_pantry_title: 'Pantry',
    help_pantry_desc: 'Manage your home ingredient stock. Update quantities after shopping.',
    // Loading
    loading_1: 'Preparing your recipes…',
    loading_2: 'Calculating your weekly budget…',
    loading_3: 'Loading your planner…',
    loading_4: 'Cook smarter with Eatsy.',
    loading_5: 'Your culinary week is being prepared…',
    loading_6: 'Syncing your shopping lists…',
    // Auth
    auth_email_required: 'Email required',
    auth_email_invalid: 'Invalid email',
    auth_password_required: 'Password required',
    auth_password_min: 'At least 6 characters',
    auth_passwords_mismatch: 'Passwords do not match',
    // Login
    login_title: 'Sign in',
    login_tagline: 'Plan. Cook. Save.',
    login_error_title: 'Login error',
    login_error_msg: 'Incorrect email or password.',
    login_forgot: 'Forgot password?',
    login_create_account: 'Create account',
    login_or: 'or',
    // Register
    register_title: 'Create account',
    register_sub: 'Join the curated table.',
    register_name_label: 'Full name',
    register_name_placeholder: 'Jane Doe',
    register_email_label: 'Email address',
    register_pwd_label: 'Password',
    register_pwd_placeholder: 'Min. 6 characters',
    register_confirm_label: 'Confirm password',
    register_btn: 'Create my account',
    register_login_link: 'Already registered? Sign in',
    register_failed: 'Registration failed',
    // Forgot password
    forgot_title: 'Forgot password?',
    forgot_sub: "Enter your email and we'll send\nyou a reset link.",
    forgot_email_label: 'Email address',
    forgot_email_placeholder: 'your@email.com',
    forgot_send_btn: 'Send link',
    forgot_back_link: '← Back to sign in',
    forgot_success_title: 'Email sent!',
    forgot_success_desc: 'Check your inbox and follow the instructions to reset your password.',
    forgot_back_to_login: 'Back to sign in',
    forgot_failed: 'Failed to send',
    // Welcome
    welcome_greeting: 'Welcome 👋',
    welcome_tagline: 'Plan · Cook · Save',
    // Lock
    lock_title: 'App locked',
    lock_sub_face: "Use Face ID\nor your device PIN",
    lock_sub_finger: "Use your fingerprint\nor your device PIN",
    lock_sub_default: "Use biometrics\nor your device PIN",
    lock_unlock: 'Unlock',
    lock_prompt: 'Unlock Eatsy',
    lock_fallback: 'Use PIN',
    lock_cancelled: 'Authentication cancelled.',
    lock_error: 'Authentication error.',
    // Onboarding
    onboarding_skip: 'Skip',
    onboarding_slide1_title: 'Plan your week',
    onboarding_slide1_desc: 'Organise breakfast, lunch and dinner for each day. Your meal planner always at hand.',
    onboarding_slide2_title: 'Master your budget',
    onboarding_slide2_desc: 'Track your food spending week by week. Eatsy calculates the cost of each meal automatically.',
    onboarding_slide3_title: 'Cook smart',
    onboarding_slide3_desc: 'Generate your shopping list in one click, manage your pantry and find all your recipes in one place.',
    onboarding_next: 'Next',
    onboarding_start: 'Get started',
    // Settings — security & help
    settings_security: 'SECURITY',
    settings_biometric_face: 'Face ID',
    settings_biometric_fingerprint: 'Fingerprint',
    settings_biometric_pin: 'PIN',
    settings_biometric_default: 'Biometrics',
    settings_biometric_sub_on: 'Locks app after 30s in background',
    settings_biometric_sub_off: 'Not available on this device',
    settings_biometric_confirm: 'Confirm activation',
    settings_help_show: 'Show user guide',
    settings_help_hide: 'Hide guide',
    settings_terms_show: 'Read terms of use',
    settings_terms_hide: 'Hide terms',
    // Add recipe
    add_recipe_title_new: 'New recipe',
    add_recipe_title_edit: 'Edit recipe',
    add_recipe_change_photo: 'Change',
    add_recipe_add_photo: 'Add a photo',
    add_recipe_photo_hint: 'Optional · JPG, PNG',
    add_recipe_general: 'General info',
    add_recipe_name_label: 'Recipe name *',
    add_recipe_name_placeholder: 'E.g.: Roast chicken with herbs',
    add_recipe_prep_label: 'Prep (min)',
    add_recipe_cook_label: 'Cook (min)',
    add_recipe_servings_label: 'Servings',
    add_recipe_category: 'Category',
    add_recipe_ingredients: 'Ingredients',
    add_recipe_quantity: 'Quantity',
    add_recipe_unit: 'Unit',
    add_recipe_add_ingredient: 'Add ingredient',
    add_recipe_add_step: 'Add step',
    add_recipe_save_new: 'Create recipe',
    add_recipe_save_edit: 'Save changes',
    add_recipe_incomplete_title: 'Incomplete ingredient',
    add_recipe_incomplete_msg: 'All ingredients must have a name.',
    add_recipe_name_required_msg: 'Please enter a name for the recipe.',
    add_recipe_meal_type: 'Meal type',
    add_recipe_desc_label: 'Description',
    add_recipe_desc_placeholder: 'Short description...',
    add_recipe_ing_name: 'Name',
    add_recipe_ingredient_n: 'Ingredient',
    add_recipe_step_placeholder: 'Describe step {n}...',
    add_recipe_instructions: 'Instructions',
    // Recipe detail
    recipe_stat_prep: 'Prep.',
    recipe_stat_cook: 'Cook',
    recipe_stat_servings: 'Servings',
    recipe_stat_per_person: 'Per serving',
    recipe_total_cost: 'Total recipe cost',
    recipe_ingredient_total: 'Ingredients total',
    recipe_deduct_btn: 'Deduct',
    recipe_start_cooking: 'Start cooking',
    recipe_stock_empty: 'Insufficient stock',
    recipe_stock_empty_msg: 'No ingredients found in your pantry.',
    recipe_deduct_title: 'Deduct from stock',
    recipe_deduct_done: 'Stock updated',
    recipe_deduct_done_msg: 'Ingredients have been deducted from your pantry.',
    recipe_added_shopping: 'Added to shopping',
    recipe_delete_title: 'Delete recipe',
    recipe_delete_confirm_msg: 'Delete "{name}" permanently?',
    recipe_deduct_confirm_msg: 'Deduct the ingredients of "{name}" from your pantry?',
    recipe_added_shopping_msg: '{n} ingredient(s) added to your shopping list.',
    recipe_in_stock: 'Available stock',
    recipe_stock_complete: 'complete',
    recipe_stock_partial: 'partial',
    recipe_stock_missing: 'missing',
    recipe_stock_dispo: 'in stock',
    recipe_stock_out: 'out of stock',
    recipe_shopping_list_btn: 'Shopping',
    recipe_share_btn: 'Share recipe',
    recipe_share_cost: 'Estimated cost',
    recipe_tab_ingredients: 'Ingredients',
    recipe_tab_instructions: 'Instructions',
    // Cooking
    cooking_step: 'Step',
    cooking_step_of: 'of',
    cooking_last_step: 'Last step',
    cooking_prev: 'Previous',
    cooking_finish: 'Finish',
    cooking_timer: 'Timer',
    cooking_start_timer: 'Start',
    cooking_pause_timer: 'Pause',
    cooking_all_steps: 'All steps',
    cooking_timer_done: 'Time is up!',
    cooking_recipe_done: 'Recipe is done.',
    // Budget
    budget_over_label: 'over budget',
    budget_remaining_label: 'remaining',
    budget_avg_label: 'avg / day',
    budget_limit_label: 'set limit',
    budget_per_day: 'Per day',
    budget_progress_label: 'Budget progress',
    budget_no_meals_day: 'No meals planned',
    budget_this_week: 'This\nweek',
    // Dashboard
    dashboard_over_budget: 'Over budget',
    dashboard_on_track: 'On track',
    // Food scanner
    scanner_camera_title: 'Scan a product',
    scanner_permission: 'Camera permission required',
    scanner_allow: 'Allow',
    scanner_product_not_found: 'Product not found',
    scanner_barcode_label: 'Barcode',
    scanner_rescan: 'Scan again',
    scanner_close: 'Close',
    scanner_network_error: 'Network error',
    scanner_network_error_msg: 'Unable to retrieve product information.',
    scanner_added_to_cart: 'Added to shopping',
    scanner_added_to_cart_msg: 'added to your shopping list.',
    scanner_scan_another: 'Scan another',
    scanner_added_to_stock: 'Added to stock',
    scanner_added_to_stock_msg: 'added to your pantry.',
    scanner_unknown: 'Unknown product',
    scanner_nutrition: 'Nutritional values / 100g',
    scanner_quantity: 'Quantity',
    scanner_rescan_product: 'Scan another product',
    scanner_cart_btn: 'Shopping',
    scanner_stock_btn: 'My Stock',
    scanner_energy: 'Energy',
    scanner_proteins: 'Proteins',
    scanner_carbs: 'Carbs',
    scanner_fat: 'Fat',
    // Pantry
    pantry_depleted: 'depleted',
    pantry_search_ph: 'Search ingredient…',
    pantry_filter_available: 'Available',
    pantry_filter_empty: 'Depleted',
    pantry_exhausted: 'Depleted',
    pantry_empty_title: 'Pantry empty',
    pantry_empty_no_results: 'No results',
    pantry_empty_no_match: 'No ingredients here',
    pantry_empty_desc: 'Add your available ingredients to track your stock.',
    pantry_empty_filter_desc: 'Change the filter to view your ingredients.',
    pantry_add_btn: 'Add ingredient',
    pantry_sheet_add: 'Add to stock',
    pantry_label_ingredient: 'Ingredient *',
    pantry_placeholder_ingredient: 'E.g.: Beef, Flour, Milk…',
    pantry_label_quantity: 'Quantity *',
    pantry_label_unit: 'Unit',
    pantry_save_update: 'Update',
    // Profile
    profile_title: 'Profile',
    profile_member_since: 'member since',
    profile_status_email: 'email status',
    profile_verified: 'Verified',
    profile_not_verified: 'Not verified',
    profile_change_name: 'Change your display name',
    profile_update_creds: 'Update your credentials',
    profile_verify_title: 'Verify email address',
    profile_verify_sub: 'A link will be sent to your address',
    profile_verify_sent: 'Email sent — check your inbox',
    profile_check_verified: "I've verified my email",
    profile_check_verified_sub: 'Tap here after clicking the link',
    profile_settings_link: 'Settings',
    profile_display_name_label: 'Display name',
    profile_email_label: 'Email address',
    profile_pwd_current_label: 'Current password',
    profile_pwd_new_label: 'New password',
    profile_pwd_confirm_label: 'Confirm',
    profile_pwd_current_required: 'Current password required',
    profile_pwd_new_required: 'New password required',
    profile_pwd_wrong: 'Incorrect current password',
    profile_pwd_changed: 'Your password has been changed.',
    profile_verified_success: 'Email verified ✓',
    profile_verified_msg: 'Your email address has been verified.',
    profile_not_verified_yet: 'Not yet verified',
    profile_error_profile: 'Unable to update profile',
    profile_error_pwd: 'Unable to update password',
    profile_error_verify: 'Unable to send verification email',
    profile_email_sent_title: 'Email sent',
    profile_too_many: 'Too many attempts',
    profile_too_many_msg: 'Wait a few minutes before resending.',
    profile_section_info: 'INFORMATION',
    profile_section_security: 'SECURITY',
    // Budget (new)
    budget_evolution: 'Spending trend',
    budget_over_prefix: 'Over by',
    budget_pct_used: 'used',
    budget_modal_title: 'Weekly Budget',
    budget_modal_desc: 'Set your spending limit for the week.',
    budget_modal_limit: 'Limit',
    // Dashboard / Common (new)
    dashboard_cook_btn: 'Cook',
    tabs_scanner: 'Scanner',
    common_chef: 'Chef',
    common_success: 'Success',
    // Pantry (new)
    pantry_total_label: 'total',
    pantry_available_label: 'available',
    pantry_depleted_label: 'depleted',
    pantry_ingredients_total: '{n} ingredient(s) total',
    pantry_sheet_edit: 'Edit "{name}"',
    pantry_current_stock: 'Current stock',
    pantry_save_add: 'Add',
    pantry_search_match_desc: 'No ingredient matching "{query}".',
    // Profile (new)
    profile_section_account: 'ACCOUNT INFO',
    profile_section_actions: 'ACTIONS',
    profile_edit_title: 'Edit profile',
    profile_change_pwd: 'Change password',
    profile_name_placeholder: 'Your name',
    profile_pwd_confirm_full: 'Confirm new password',
    profile_verif_link_msg: 'A verification link was sent to {email}. Click the link and come back here.',
    profile_not_verified_msg: 'Click the link in the verification email and try again.',
    // Settings (new)
    settings_data_section: 'DATA & PRIVACY',
    settings_biometric_lock: '{type} Lock',
    settings_faq_q1: "Is my data shared with third parties?",
    settings_faq_a1: "No. Your data (recipes, planner, budget) is stored on your personal Firebase account and is never shared, sold, or transmitted to third parties.",
    settings_faq_q2: "Does the app work offline?",
    settings_faq_a2: "Some recently viewed data is cached by Firebase, but most features require an internet connection to sync your data in real time.",
    settings_faq_q3: "How do I delete my account and data?",
    settings_faq_a3: "To permanently delete your account and all your data, contact support from the About section. Deletion is permanent and irreversible.",
    settings_faq_q4: "Can I use Eatsy on multiple devices?",
    settings_faq_a4: "Yes. Your data is synced via your account and accessible on all your connected devices using the same credentials.",
    settings_faq_q5: "How are recipe costs calculated?",
    settings_faq_a5: "A recipe's cost is the sum of the unit prices of its ingredients, which you enter during creation. The cost per person is then calculated by dividing by the number of servings.",
    settings_faq_q6: "Is my data secure?",
    settings_faq_a6: "Yes. Data is encrypted in transit (HTTPS) and at rest within Google Firebase's infrastructure, which is ISO 27001 and SOC 2 certified.",
    settings_terms_t1: 'Data collected',
    settings_terms_b1: "Eatsy collects your name, email address, recipes, meal plan, shopping list, budget, and pantry data. This data is necessary for the app to function properly.",
    settings_terms_t2: 'Storage & security',
    settings_terms_b2: "Your data is stored on Firebase (Google LLC), encrypted in transit (TLS) and at rest. The infrastructure is ISO 27001 and SOC 2 Type II certified.",
    settings_terms_t3: 'Data sharing',
    settings_terms_b3: "No personal data is shared, sold, or transferred to third parties for commercial purposes. Eatsy does not use advertising trackers.",
    settings_terms_t4: 'Right to deletion',
    settings_terms_b4: "You can request permanent deletion of your account and all your data at any time by contacting us. Deletion is completed within 30 days.",
    settings_terms_t5: 'Terms updates',
    settings_terms_b5: "These terms may be updated. You will be notified in the event of a significant change. Continued use of the app constitutes acceptance.",
  },
};

interface PreferencesContextType {
  language: Language;
  currency: Currency;
  darkMode: boolean;
  loaded: boolean;
  setLanguage: (l: Language) => Promise<void>;
  setCurrency: (c: Currency) => Promise<void>;
  setDarkMode: (v: boolean) => Promise<void>;
  applyRemotePrefs: (prefs: { currency?: string; language?: string; darkMode?: boolean }) => void;
  t: (key: string) => string;
  formatCurrency: (amount: number) => string;
  currencySymbol: string;
}

const PreferencesContext = createContext<PreferencesContextType>({
  language: 'fr',
  currency: 'EUR',
  darkMode: false,
  loaded: false,
  setLanguage: async () => {},
  setCurrency: async () => {},
  setDarkMode: async () => {},
  applyRemotePrefs: () => {},
  t: (k) => k,
  formatCurrency: (a) => `${a.toFixed(2)} €`,
  currencySymbol: '€',
});

export const PreferencesProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('fr');
  const [currency, setCurrencyState] = useState<Currency>('EUR');
  const [darkMode, setDarkModeState] = useState(false);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const load = async () => {
      try {
        const [lang, curr, dark] = await Promise.all([
          AsyncStorage.getItem('eatsy_lang'),
          AsyncStorage.getItem('eatsy_currency'),
          AsyncStorage.getItem('eatsy_darkmode'),
        ]);
        if (lang === 'fr' || lang === 'en') setLanguageState(lang);
        if (curr === 'EUR' || curr === 'MAD') setCurrencyState(curr);
        if (dark === 'true') setDarkModeState(true);
      } catch (e) {
        // AsyncStorage unavailable, use defaults
      } finally {
        setLoaded(true);
      }
    };
    load();
  }, []);

  const setLanguage = async (l: Language) => {
    setLanguageState(l);
    try { await AsyncStorage.setItem('eatsy_lang', l); } catch {}
  };

  const setCurrency = async (c: Currency) => {
    setCurrencyState(c);
    try { await AsyncStorage.setItem('eatsy_currency', c); } catch {}
  };

  const setDarkMode = async (v: boolean) => {
    setDarkModeState(v);
    try { await AsyncStorage.setItem('eatsy_darkmode', v ? 'true' : 'false'); } catch {}
  };

  const applyRemotePrefs = (prefs: { currency?: string; language?: string; darkMode?: boolean }) => {
    if (prefs.currency === 'EUR' || prefs.currency === 'MAD') setCurrencyState(prefs.currency);
    if (prefs.language === 'fr' || prefs.language === 'en') setLanguageState(prefs.language);
    if (typeof prefs.darkMode === 'boolean') setDarkModeState(prefs.darkMode);
  };

  const t = (key: string): string => TRANSLATIONS[language][key] ?? TRANSLATIONS['fr'][key] ?? key;

  const formatCurrency = (amount: number): string => {
    if (currency === 'EUR') return `${amount.toFixed(2)} €`;
    return `${amount.toFixed(2)} MAD`;
  };

  const currencySymbol = currency === 'EUR' ? '€' : 'MAD';

  return (
    <PreferencesContext.Provider value={{ language, currency, darkMode, loaded, setLanguage, setCurrency, setDarkMode, applyRemotePrefs, t, formatCurrency, currencySymbol }}>
      {children}
    </PreferencesContext.Provider>
  );
};

export const usePreferences = () => useContext(PreferencesContext);

export const useColors = () => {
  const { darkMode } = useContext(PreferencesContext);
  return darkMode ? DarkColors : Colors;
};
